spring:
  r2dbc:
    url: r2dbc:h2:mem:///healthservicedb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    initialization-mode: never

logging:
  level:
    io.r2dbc.h2.QUERY: DEBUG # for queries
    io.r2dbc.h2.PARAM: DEBUG # for parameters